version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: parc-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: parc_informatique
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ../database/02-seed-demo-data.sql:/docker-entrypoint-initdb.d/02-seed-demo-data.sql:ro

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: parc-backend
    depends_on:
      - postgres
    environment:
      SERVER_PORT: 8080
      DB_URL: jdbc:postgresql://postgres:5432/parc_informatique
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: change-me-with-a-long-random-secret-key-please-123456789
      JWT_ACCESS_EXPIRATION_MINUTES: 30
      JWT_REFRESH_EXPIRATION_DAYS: 7
      UPLOAD_BASE_PATH: /app/uploads
      APP_BASE_URL: http://localhost:8080
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_FROM: no-reply@parc.local
      MAIL_SMTP_AUTH: "false"
      MAIL_SMTP_STARTTLS: "false"
      MAIL_FAIL_ON_ERROR: "false"
    ports:
      - "8080:8080"
    volumes:
      - app_uploads:/app/uploads

volumes:
  postgres_data:
  app_uploads:
